In [2]:
import numpy as np

In [3]:
my_list = [10, 20, 30, 40]

In [5]:
test_list = my_list + my_list

In [6]:
test_list

[10, 20, 30, 40, 10, 20, 30, 40]

In [8]:
test_list = my_list * 3
test_list

[10, 20, 30, 40, 10, 20, 30, 40, 10, 20, 30, 40]

In [14]:
my_np_list = np.array([10, 20, 30, 40])
my_np_list

array([10, 20, 30, 40])

In [17]:
my_np_test_list = my_np_list + my_np_list
my_np_test_list

array([20, 40, 60, 80])

In [18]:
my_np_test_list = my_np_list * 3
my_np_test_list

array([ 30,  60,  90, 120])

In [22]:
my_np_list.mean()

np.float64(25.0)

In [27]:
my_np_list.min()

np.int64(10)

In [34]:
my_np_list.sum()

np.int64(100)

In [35]:
# arange & indexing

In [36]:
list(range(10, 20, 2))

[10, 12, 14, 16, 18]

In [37]:
np.arange(10, 20, 2)

array([10, 12, 14, 16, 18])

In [38]:
np_array = np.arange(0, 10)

In [42]:
np_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
np_array[0]

np.int64(0)

In [45]:
np_array[-1]

np.int64(9)

In [47]:
np_array[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [48]:
#random

In [49]:
np.random.randn(5)

array([ 0.28731864, -0.4428087 ,  0.48217379, -2.15844696, -1.08512083])

In [50]:
np.random.randn(5, 5)

array([[ 2.33244669, -1.73787473,  1.30221249, -0.1837285 ,  0.27542625],
       [ 0.30215564,  2.06510052, -0.25523128, -0.44565911, -1.19749039],
       [ 1.70346224,  0.33149738,  3.0076216 ,  1.57863109, -0.86579586],
       [-0.47815855,  2.18153808, -0.45903972,  0.77432437,  0.15516031],
       [-0.57898293, -0.40805841,  0.27079984,  0.33019343,  0.31820343]])

In [51]:
np.random.randint(0, 100, 5)

array([61, 47, 52, 97, 38], dtype=int32)