In [1]:
import numpy as np

In [2]:
np_matrix = np.array([[1, 2],[3, 4]])
np_matrix

array([[1, 2],
       [3, 4]])

In [3]:
np_matrix[0, 1]

np.int64(2)

In [4]:
np_matrix.sum()

np.int64(10)

In [5]:
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [6]:
np.ones((4, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [7]:
np.random.random((3, 4))

array([[0.12457328, 0.75014966, 0.46873   , 0.25249581],
       [0.13540419, 0.24768749, 0.85100018, 0.42367353],
       [0.19858749, 0.41334575, 0.88393512, 0.95164825]])

In [8]:
#matrix arithmetic

In [9]:
first_matrix = np.array([[10, 20],[30, 40]])
second_matrix = np.array([[15, 25],[35, 45]])

In [10]:
first_matrix + second_matrix

array([[25, 45],
       [65, 85]])

In [11]:
first_matrix * second_matrix

array([[ 150,  500],
       [1050, 1800]])

In [12]:
third_matrix = np.array([[100, 200]]) # or np.array([[100],[200]])

In [13]:
first_matrix + third_matrix

array([[110, 220],
       [130, 240]])

In [14]:
first_matrix.shape

(2, 2)

In [15]:
# dot product

In [20]:
dot_matrix1 = np.array([[10, 20, 30]])
dot_matrix2 = np.array([[1, 2], [3, 4], [5, 6]])

In [21]:
dot_matrix1

array([[10, 20, 30]])

In [22]:
dot_matrix1.shape

(1, 3)

In [23]:
dot_matrix2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [24]:
dot_matrix2.shape

(3, 2)

In [25]:
dot_matrix1.dot(dot_matrix2)

array([[220, 280]])

In [26]:
dot_matrix1.dot(dot_matrix2).shape

(1, 2)