In [1]:
import numpy as np

In [2]:
array = np.random.randint(1, 100, 10)

In [3]:
array

array([73, 50,  7, 20, 84, 58, 57, 92, 54, 27], dtype=int32)

In [4]:
array < 25

array([False, False,  True,  True, False, False, False, False, False,
       False])

In [8]:
array[array < 25]

array([ 7, 20], dtype=int32)

In [9]:
# transpose and reshape

In [10]:
matrix_array = np.array([[1, 2], [3, 4], [5, 6]])

In [11]:
matrix_array

array([[1, 2],
       [3, 4],
       [5, 6]])

In [13]:
matrix_array.T # = matrix_array.transpose()

array([[1, 3, 5],
       [2, 4, 6]])

In [16]:
reshape_array

array([[0.86128247],
       [0.43056581],
       [0.27548414],
       [0.89754375],
       [0.19731931],
       [0.39857385]])

In [17]:
reshape_array.reshape(3, 2)

array([[0.86128247, 0.43056581],
       [0.27548414, 0.89754375],
       [0.19731931, 0.39857385]])

In [19]:
# math example
# 3x + 6y = 21 and 6x + y = 20

In [20]:
A = np.array([[3, 6], [6, 1]])

In [21]:
B = np.array([21, 20])

In [22]:
result = np.linalg.solve(A, B)

In [23]:
result

array([3., 2.])